# Generated by Django 5.2.7 on 2025-10-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASAChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_corta', models.TextField(max_length=500)),
                ('descripcion_completa', models.TextField()),
                ('categoria_nasa', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('estado', models.CharField(default='En desarrollo', max_length=50)),
            ],
            options={
                'verbose_name': 'NASA Challenge',
                'verbose_name_plural': 'NASA Challenges',
            },
        ),
        migrations.CreateModel(
            name='Innovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tecnologia', models.CharField(max_length=100)),
                ('aplicacion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='innovaciones/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innovaciones', to='nasa_project.nasachallenge')),
            ],
            options={
                'verbose_name': 'Innovación',
                'verbose_name_plural': 'Innovaciones',
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='nasa_project.nasachallenge')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'ordering': ['orden', 'fecha'],
            },
        ),
    ]
