# Generated by Django 5.2.7 on 2025-10-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(help_text='Clase de Bootstrap Icons', max_length=50)),
                ('color', models.CharField(default='#0ea5e9', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoría RAEE',
                'verbose_name_plural': 'Categorías RAEE',
            },
        ),
        migrations.CreateModel(
            name='InfoRAEE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='raee/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacion', to='raee_info.categoriaraee')),
            ],
            options={
                'verbose_name': 'Información RAEE',
                'verbose_name_plural': 'Información RAEE',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRecuperable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('simbolo_quimico', models.CharField(blank=True, max_length=10)),
                ('porcentaje_recuperacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_mercado', models.DecimalField(decimal_places=2, help_text='USD por kg', max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='raee_info.categoriaraee')),
            ],
            options={
                'verbose_name': 'Material Recuperable',
                'verbose_name_plural': 'Materiales Recuperables',
            },
        ),
    ]
