# Generated by Django 5.2.7 on 2025-10-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoReciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('centro', 'Centro de Reciclaje'), ('movil', 'Punto Móvil'), ('comercio', 'Comercio Adherido'), ('cooperativa', 'Cooperativa')], max_length=20)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('horario', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Punto de Reciclaje',
                'verbose_name_plural': 'Puntos de Reciclaje',
            },
        ),
        migrations.CreateModel(
            name='Recoleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_residuos', models.CharField(max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recolecciones', to='puntos_reciclaje.puntoreciclaje')),
            ],
            options={
                'verbose_name': 'Recolección',
                'verbose_name_plural': 'Recolecciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
