# Generated by Django 5.2.7 on 2025-10-04 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactoAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('toneladas_recicladas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2_evitado', models.DecimalField(decimal_places=2, help_text='Toneladas de CO2', max_digits=10)),
                ('empleos_generados', models.IntegerField()),
                ('dispositivos_procesados', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Impacto Ambiental',
                'verbose_name_plural': 'Impacto Ambiental',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('fundador', 'Fundador'), ('cooperativista', 'Cooperativista'), ('voluntario', 'Voluntario')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('especialidad', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='miembros/')),
                ('biografia', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('planificacion', 'En Planificación'), ('ejecucion', 'En Ejecución'), ('completado', 'Completado'), ('pausado', 'Pausado')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('responsables', models.ManyToManyField(related_name='proyectos', to='cooperativa.miembro')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
